spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


##################################################################################
server:
  port: ${SERVER_PORT:8080}