import React from "react";
import "bootstrap/dist/css/bootstrap.css";
import { DataProvider } from '../context/DataContext';

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DataProvider>
        {children}
        </DataProvider>
      </body>
    </html>
  );
}

export { metadata };
export default RootLayout;
